import { expect, test } from "@playwright/test";
import { readFile } from "node:fs/promises";
import { registerViaApi } from "./helpers";

const presets = ["linear", "double", "percentage", "top-backoff", "reset", "manual-ab"];

test("import, edit, export and reload a versioned program file", async ({ page }) => {
  await registerViaApi(page, "program-file");
  await page.goto("/programs/editor/new");
  await page.getByText("Presets and program files", { exact: true }).click();
  const file = JSON.parse(await readFile("examples/programs/double.magni.json", "utf8"));
  await page.getByLabel("Import program file", { exact: true }).setInputFiles({ name: "double.magni.json", mimeType: "application/json", buffer: Buffer.from(JSON.stringify(file)) });
  await expect(page.getByLabel("Program name", { exact: true })).toHaveValue(file.name);
  await page.getByLabel("Program name", { exact: true }).fill("My imported program");
  const downloadPromise = page.waitForEvent("download");
  await page.getByRole("button", { name: "Export program file", exact: true }).click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toBe("My imported program.magni.json");
  const exported = JSON.parse(await readFile((await download.path())!, "utf8"));
  expect(exported).toEqual({ ...file, name: "My imported program" });
  await page.getByLabel("Import program file", { exact: true }).setInputFiles({ name: "unsupported.json", mimeType: "application/json", buffer: Buffer.from(JSON.stringify({ ...file, schemaVersion: 99 })) });
  await expect(page.getByRole("alert").filter({ hasText: "Check this program file" })).toBeVisible();
  await expect(page.getByLabel("Program name", { exact: true })).toHaveValue("My imported program");
  await page.getByRole("button", { name: "Save now", exact: true }).click();
  await expect(page.getByText("Draft saved", { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByLabel("Program name", { exact: true })).toHaveValue("My imported program");
  await page.getByRole("button", { name: "Progression & preview", exact: true }).click();
  await expect(page.getByRole("combobox", { name: "Progression condition", exact: true })).toHaveValue("double_progression");
});

test("author a custom double progression program, preview, reload and activate", async ({ page }, info) => {
  test.setTimeout(90_000);
  await registerViaApi(page, "direct-editor");
  await page.goto("/programs");
  await page.getByRole("link", { name: "Custom program", exact: true }).click();
  await page.getByLabel("Program name", { exact: true }).fill("Exact double progression");
  await page.getByLabel("Repeat cycles").fill("3");
  await page.getByRole("button", { name: "Prescriptions", exact: true }).click();
  await page.getByRole("button", { name: "Add exercise", exact: true }).click();
  await page.getByLabel("Exercise name", { exact: true }).fill("Dumbbell row");
  await expect(page.getByLabel("Working load (lb)", { exact: true })).toHaveValue("40");
  await page.getByRole("button", { name: "Progression & preview", exact: true }).click();
  await page.getByRole("combobox", { name: "Progression condition", exact: true }).selectOption("double_progression");
  await page.getByLabel("Set 3 reps", { exact: true }).fill("11");
  await expect(page.getByRole("status", { name: "Progression preview result" })).toContainText(/hold/i);
  const controlSizes = await page.locator("select.touch-target:visible, button.touch-target:visible, input.touch-target:visible").evaluateAll(elements => elements.map(element => ({label: element.getAttribute("aria-label") || element.textContent?.slice(0,40),height:element.getBoundingClientRect().height,width:element.getBoundingClientRect().width})));
  expect(controlSizes.filter(size => size.height < 44 || size.width < 44)).toEqual([]);
  await page.screenshot({ path: info.outputPath("editor-double-hold.png"), fullPage: true });
  await page.evaluate(() => { document.documentElement.dataset.theme = "dark"; });
  await page.screenshot({ path: info.outputPath("editor-double-dark.png"), fullPage: true });
  await page.evaluate(() => { document.documentElement.dataset.theme = "light"; document.documentElement.style.fontSize = "20px"; });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: info.outputPath("editor-enlarged-text.png"), fullPage: true });
  await page.evaluate(() => { document.documentElement.style.fontSize = ""; });
  await page.getByLabel("Set 3 reps", { exact: true }).fill("12");
  await expect(page.getByRole("status", { name: "Progression preview result" })).toContainText("42.5");
  await page.getByRole("button", { name: "Save now", exact: true }).click();
  await expect(page.getByText("Draft saved", { exact: true })).toBeVisible();
  const url = page.url();
  await page.reload();
  await expect(page.getByLabel("Program name", { exact: true })).toHaveValue("Exact double progression");
  await page.getByRole("button", { name: "Progression & preview", exact: true }).click();
  await expect(page.getByRole("combobox", { name: "Progression condition", exact: true })).toHaveValue("double_progression");
  await page.getByRole("button", { name: "Review & activate", exact: true }).click();
  for (const weekday of ["Sun", "Tue", "Thu", "Sat"]) await page.getByRole("button", { name: weekday, exact: true }).click();
  await page.screenshot({ path: info.outputPath("editor-review.png"), fullPage: true });
  const activation = page.waitForResponse(response => response.url().endsWith("/activate") && response.request().method() === "POST");
  await page.getByRole("button", { name: "Activate program", exact: true }).click();
  expect((await activation).ok()).toBe(true);
  await expect(page.getByText("Program activated", { exact: true })).toBeVisible();
  await page.goto(url);
  await expect(page.getByText("Program activated", { exact: true })).toBeVisible();
  await page.getByRole("link", { name: "Train this program" }).click();
  await expect(page.getByText("Dumbbell row", { exact: true })).toBeVisible();
  const start = page.waitForResponse(response => /\/api\/programs\/\d+\/sessions$/.test(response.url()) && response.request().method() === "POST");
  await page.getByRole("button", { name: "Start Workout", exact: true }).click();
  const session = await (await start).json();
  expect(session.sets).toHaveLength(3);
  expect(session.sets.map((set: {calculated_weight:number}) => set.calculated_weight)).toEqual([40,40,40]);
  expect(session.sets.every((set: {editor_json:string}) => JSON.parse(set.editor_json).rule.condition.type === "double_progression")).toBe(true);
  await expect(page.getByRole("heading", { name: "Dumbbell row", exact: true })).toBeVisible();
  await page.screenshot({ path: info.outputPath("editor-trained-prescription.png"), fullPage: true });
});

for (const preset of presets) test(`customize, copy, reload and activate ${preset}`, async ({ page }, info) => {
  test.setTimeout(90_000);
  await registerViaApi(page, `preset-${preset}`);
  await page.goto("/programs/editor/new");
  await page.getByText("Presets and program files", { exact: true }).click();
  await page.getByRole("combobox", { name: "Optional starting structure", exact: true }).selectOption(preset);
  await page.getByRole("button", { name: "Apply preset", exact: true }).click();
  await page.getByLabel("Program name", { exact: true }).fill(`My ${preset}`);
  await page.getByRole("button", { name: "Copy week", exact: true }).click();
  await page.getByLabel("Week name", { exact: true }).fill("Override week");
  await page.getByRole("button", { name: "Prescriptions", exact: true }).click();
  await page.getByLabel("Set 1 minimum reps", { exact: true }).fill("4");
  await page.getByRole("button", { name: "Progression & preview", exact: true }).click();
  await expect(page.getByRole("status", { name: "Progression preview result" })).not.toBeEmpty();
  await page.getByRole("button", { name: "Save now", exact: true }).click();
  await expect(page.getByText("Draft saved", { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByLabel("Program name", { exact: true })).toHaveValue(`My ${preset}`);
  await page.getByRole("combobox", { name: "Week", exact: true }).selectOption({ label: "Override week" });
  await page.getByRole("button", { name: "Prescriptions", exact: true }).click();
  await expect(page.getByLabel("Set 1 minimum reps", { exact: true })).toHaveValue("4");
  if (preset === "top-backoff") await page.screenshot({ path: info.outputPath("editor-top-backoff.png"), fullPage: true });
  await page.getByRole("button", { name: "Review & activate", exact: true }).click();
  await page.getByRole("button", { name: "Activate program", exact: true }).click();
  await expect(page.getByText("Program activated", { exact: true })).toBeVisible();
  await expect(page.locator("body")).not.toHaveText(/Application error/);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});
