"use client";
import Link from "next/link";
import { ChevronsUpDown, ChevronRight } from "lucide-react";
import { useRef, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import type { CandidateObservation, ExerciseDetail, ProgressHome } from "@/features/progress/types";
import { actualResult, asFinderItem, exerciseHref } from "./ExerciseRows";
import { representativeSet } from "./representative-set";
import { ExerciseChooser } from "./ExerciseChooser";
import { RecordedRepsChart } from "./ExerciseProgressChart";
import { ProgressDate, progressButton, progressInput } from "./ProgressChrome";
import { progressUrl, workoutEvidenceHref, type ProgressMetric } from "./navigation";

type Period = "4w" | "12w" | "all";
export function ProgressOverview({ home, period, currentHref: initialHref, initialMetric, selectedKey = "", selectedName, detail, unlinked = [], selectionError }: { home: ProgressHome; period: Period; currentHref: string; initialMetric?: ProgressMetric; selectedKey?: string; selectedName?: string; detail?: ExerciseDetail | null; unlinked?: CandidateObservation[]; selectionError?: string }) {
  const router = useRouter();
  const [choosing, setChoosing] = useState(false), [pending, startTransition] = useTransition();
  const trigger = useRef<HTMLButtonElement>(null);
  const [metricState, setMetricState] = useState({ href: initialHref, value: initialMetric });
  // URL changes (including Back) replace presentation state without replacing controls.
  if (metricState.href !== initialHref) setMetricState({ href: initialHref, value: initialMetric });
  const metric = metricState.href === initialHref ? metricState.value : initialMetric;
  const currentHref = metric ? progressUrl("/history", { exercise: selectedKey, period, metric }) : initialHref;
  const initialItems = [...home.pinned.map(asFinderItem), ...home.recent].filter((item, index, all) => all.findIndex(candidate => candidate.key === item.key) === index).slice(0, 7);
  const name = detail?.exercise.name ?? selectedName ?? initialItems.find(item => item.key === selectedKey)?.name;
  const volume = Math.round(home.activity.volumeLb).toLocaleString();
  const missingAllLoads = home.activity.recordedSets > 0 && home.activity.missingWeightSets === home.activity.recordedSets;
  const isUnlinked = selectedKey.startsWith("u:");
  function closeChooser() { setChoosing(false); requestAnimationFrame(() => trigger.current?.focus()); }
  function navigate(key: string, nextPeriod = period, nextMetric = metric) { startTransition(() => router.push(progressUrl("/history", { exercise: key, period: nextPeriod, metric: nextMetric }), { scroll: false })); }
  const periodControl = <label className="min-w-0"><span className="sr-only">Period</span><select aria-label="Period" value={period} onChange={event => navigate(selectedKey, event.target.value as Period)} className={progressInput}><option value="4w">4 weeks</option><option value="12w">12 weeks</option><option value="all">All time</option></select></label>;
  const allRecordsHref = detail ? progressUrl(`/history/exercises/${encodeURIComponent(selectedKey)}`, { from: detail.from, to: detail.to, returnTo: currentHref }) : exerciseHref(selectedKey, currentHref);
  return <div className="safe-x flex flex-col gap-3 py-4">
    <header className="flex items-center justify-between gap-3"><h1 className="display text-4xl">Progress</h1><Link href="/workouts" className={progressButton}>History</Link></header>
    <button ref={trigger} type="button" aria-label="Choose exercise" aria-haspopup="dialog" aria-expanded={choosing} onClick={() => setChoosing(true)} className="touch-target flex w-full items-center justify-between gap-3 rounded-xl border border-line bg-surface px-4 py-3 text-left text-foreground focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand"><span className="min-w-0"><span className="display block break-words text-2xl leading-7">{name || "Choose an exercise"}</span><span className="mt-1 block text-xs font-normal text-muted">{isUnlinked ? "Matching records · choose which belong together" : "Change exercise"}</span></span><ChevronsUpDown aria-hidden="true" size={20} className="shrink-0 text-muted" /></button>
    {!!home.pinned.length && <nav aria-label="Favorite exercises" className="flex flex-wrap gap-2">{home.pinned.slice(0, 3).map(exercise => <button type="button" key={exercise.id} aria-pressed={selectedKey === `e:${exercise.id}`} onClick={() => navigate(`e:${exercise.id}`)} className={`touch-target inline-flex max-w-full items-center justify-center rounded-full border px-3 py-2 text-sm font-semibold focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand disabled:opacity-50 ${selectedKey === `e:${exercise.id}` ? "border-brand-line bg-brand-soft text-brand-strong" : "border-line bg-surface text-muted"}`}><span className="break-words">{exercise.name}</span></button>)}</nav>}
    {pending && <p role="status" className="text-sm text-muted">Updating chart…</p>}
    {detail ? <RecordedRepsChart points={detail.chart.points} truncated={detail.chart.truncated} currentHref={currentHref} overview periodControl={periodControl} metric={metric} onMetricChange={next => { setMetricState({ href: initialHref, value: next }); navigate(selectedKey, period, next); }} /> : <section className="card p-4"><div className="flex justify-end">{periodControl}</div><h2 className="display mt-3 text-2xl">{selectionError ? "Exercise unavailable" : isUnlinked ? "Keep matching records separate" : "Your exercise progress"}</h2><p className="mt-2 text-sm leading-6 text-muted">{selectionError || (isUnlinked ? "These records share a name. Choose which workouts describe one exercise before comparing them in a graph." : "Choose an exercise to see its recorded progress. Search also finds exercises from older workouts.")}</p><div className="mt-3 flex flex-wrap gap-2">{isUnlinked && !selectionError ? <><Link href={progressUrl("/history/follow", { key: selectedKey, name, returnTo: currentHref })} className={progressButton}>Follow as one exercise</Link><Link href={allRecordsHref} className={progressButton}>Review matching records</Link></> : <button type="button" onClick={() => setChoosing(true)} className={progressButton}>Find an exercise</button>}</div></section>}
    {(detail || unlinked.length > 0) && <section aria-labelledby="recent-workouts-heading"><h2 id="recent-workouts-heading" className="display text-2xl">Recent workouts</h2><ul className="divide-y divide-line" aria-label="Recent exercise workouts">{detail ? detail.observations.items.slice(0, 2).map(observation => { const set = representativeSet(observation.sets); return <li key={observation.sessionId}><Link href={workoutEvidenceHref(observation.sessionId, currentHref)} className="touch-target flex items-center justify-between gap-3 py-3"><span className="min-w-0"><span className="block text-base font-semibold"><ProgressDate date={observation.date} short /></span><span className="mt-1 block break-words text-sm text-muted">{observation.workoutName}</span></span><span className="min-w-0 text-right text-sm">{set ? <>{set.reps} reps · {set.weight === null ? "load not recorded" : `${set.weight} ${set.unit}`}<span className="mt-1 block text-xs text-muted">{set.reps === 0 ? "Attempt" : set.weight !== null && set.weight > 0 ? "Heaviest set" : "Most reps"} · {observation.recordedSets} {observation.recordedSets === 1 ? "set" : "sets"}</span></> : "No actual sets"}</span><ChevronRight aria-hidden="true" size={16} className="shrink-0 text-faint" /></Link></li>; }) : unlinked.slice(0, 2).map(observation => <li key={observation.id}><Link href={workoutEvidenceHref(observation.sessionId, currentHref)} className="touch-target flex items-center justify-between gap-3 py-3"><span className="min-w-0"><span className="block text-base font-semibold"><ProgressDate date={observation.date} short /></span><span className="mt-1 block break-words text-sm text-muted">{observation.workoutName}</span></span><span className="text-right text-sm">{actualResult(observation.latest)}</span></Link></li>)}</ul>{detail && !detail.observations.items.length && <p className="mt-2 text-sm text-muted">No recorded workouts in this date range.</p>}<Link href={allRecordsHref} className="touch-target mt-1 flex items-center justify-center text-sm font-semibold text-brand-strong">All recorded workouts{detail ? ` (${detail.totals.sessions})` : ""}</Link></section>}
    <details className="mt-1 rounded-xl border border-line px-3"><summary className="touch-target cursor-pointer py-3 text-sm font-semibold text-muted">Recorded activity</summary><section className="pb-4" aria-label="Recorded activity"><dl className="grid grid-cols-3 gap-3"><div role="group" aria-label={`${home.activity.sessions} recorded workouts`}><dt className="text-xs text-muted">Workouts</dt><dd className="display text-2xl">{home.activity.sessions}</dd></div><div role="group" aria-label={`${home.activity.recordedSets} recorded sets`}><dt className="text-xs text-muted">Recorded sets</dt><dd className="display text-2xl">{home.activity.recordedSets}</dd></div><div role="group" aria-label={missingAllLoads ? "No recorded load volume" : `${volume} ${home.activity.usesKilograms ? "lb equivalent" : "lb"} recorded volume`}><dt className="text-xs text-muted">Volume · {home.activity.usesKilograms ? "lb equiv." : "lb"}</dt><dd className="display break-words text-2xl">{missingAllLoads ? "—" : volume}</dd></div></dl><p className="mt-3 text-sm text-muted">{home.activity.from ? <><ProgressDate date={home.activity.from} />–</> : "All history through "}<ProgressDate date={home.activity.to} /></p>{home.activity.usesKilograms && <p className="mt-2 text-sm text-muted">Combined external-load volume uses lb equivalent. Workout details keep original units.</p>}{home.activity.missingWeightSets > 0 && <p className="mt-2 text-sm text-muted">Load not recorded for {home.activity.missingWeightSets} sets; excluded from volume.</p>}{home.activity.emptySessions > 0 && <p className="mt-2 text-sm text-muted">{home.activity.emptySessions} finished workouts have no recorded sets.</p>}</section></details>
    {choosing && <ExerciseChooser currentHref={currentHref} initialItems={initialItems} selectedKey={selectedKey} onClose={closeChooser} onChoose={key => { closeChooser(); navigate(key); }} />}
  </div>;
}
